// Generated by gencpp from file uart/uart_srv.msg
// DO NOT EDIT!


#ifndef UART_MESSAGE_UART_SRV_H
#define UART_MESSAGE_UART_SRV_H

#include <ros/service_traits.h>


#include <uart/uart_srvRequest.h>
#include <uart/uart_srvResponse.h>


namespace uart
{

struct uart_srv
{

typedef uart_srvRequest Request;
typedef uart_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct uart_srv
} // namespace uart


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uart::uart_srv > {
  static const char* value()
  {
    return "4419faef08a11bbf3149cc3c8450f3a1";
  }

  static const char* value(const ::uart::uart_srv&) { return value(); }
};

template<>
struct DataType< ::uart::uart_srv > {
  static const char* value()
  {
    return "uart/uart_srv";
  }

  static const char* value(const ::uart::uart_srv&) { return value(); }
};


// service_traits::MD5Sum< ::uart::uart_srvRequest> should match 
// service_traits::MD5Sum< ::uart::uart_srv > 
template<>
struct MD5Sum< ::uart::uart_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uart::uart_srv >::value();
  }
  static const char* value(const ::uart::uart_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uart::uart_srvRequest> should match 
// service_traits::DataType< ::uart::uart_srv > 
template<>
struct DataType< ::uart::uart_srvRequest>
{
  static const char* value()
  {
    return DataType< ::uart::uart_srv >::value();
  }
  static const char* value(const ::uart::uart_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uart::uart_srvResponse> should match 
// service_traits::MD5Sum< ::uart::uart_srv > 
template<>
struct MD5Sum< ::uart::uart_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uart::uart_srv >::value();
  }
  static const char* value(const ::uart::uart_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uart::uart_srvResponse> should match 
// service_traits::DataType< ::uart::uart_srv > 
template<>
struct DataType< ::uart::uart_srvResponse>
{
  static const char* value()
  {
    return DataType< ::uart::uart_srv >::value();
  }
  static const char* value(const ::uart::uart_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UART_MESSAGE_UART_SRV_H
