// Generated by gencpp from file uart/uart_srv2Request.msg
// DO NOT EDIT!


#ifndef UART_MESSAGE_UART_SRV2REQUEST_H
#define UART_MESSAGE_UART_SRV2REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uart
{
template <class ContainerAllocator>
struct uart_srv2Request_
{
  typedef uart_srv2Request_<ContainerAllocator> Type;

  uart_srv2Request_()
    : input()  {
    }
  uart_srv2Request_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _input_type;
  _input_type input;




  typedef boost::shared_ptr< ::uart::uart_srv2Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uart::uart_srv2Request_<ContainerAllocator> const> ConstPtr;

}; // struct uart_srv2Request_

typedef ::uart::uart_srv2Request_<std::allocator<void> > uart_srv2Request;

typedef boost::shared_ptr< ::uart::uart_srv2Request > uart_srv2RequestPtr;
typedef boost::shared_ptr< ::uart::uart_srv2Request const> uart_srv2RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uart::uart_srv2Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uart::uart_srv2Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uart

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'uart': ['/home/odroid/cv_vision/src/uart/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uart::uart_srv2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uart::uart_srv2Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uart::uart_srv2Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uart::uart_srv2Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uart::uart_srv2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uart::uart_srv2Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uart::uart_srv2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd76d87c8b5a6df7f98d6fac7425412";
  }

  static const char* value(const ::uart::uart_srv2Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd76d87c8b5a6dfULL;
  static const uint64_t static_value2 = 0x7f98d6fac7425412ULL;
};

template<class ContainerAllocator>
struct DataType< ::uart::uart_srv2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uart/uart_srv2Request";
  }

  static const char* value(const ::uart::uart_srv2Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uart::uart_srv2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] input\n\
";
  }

  static const char* value(const ::uart::uart_srv2Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uart::uart_srv2Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uart_srv2Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uart::uart_srv2Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uart::uart_srv2Request_<ContainerAllocator>& v)
  {
    s << indent << "input[]" << std::endl;
    for (size_t i = 0; i < v.input.size(); ++i)
    {
      s << indent << "  input[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.input[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UART_MESSAGE_UART_SRV2REQUEST_H
