// Generated by gencpp from file uart/uart_srvRequest.msg
// DO NOT EDIT!


#ifndef UART_MESSAGE_UART_SRVREQUEST_H
#define UART_MESSAGE_UART_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uart
{
template <class ContainerAllocator>
struct uart_srvRequest_
{
  typedef uart_srvRequest_<ContainerAllocator> Type;

  uart_srvRequest_()
    : input()  {
    }
  uart_srvRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_type;
  _input_type input;




  typedef boost::shared_ptr< ::uart::uart_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uart::uart_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct uart_srvRequest_

typedef ::uart::uart_srvRequest_<std::allocator<void> > uart_srvRequest;

typedef boost::shared_ptr< ::uart::uart_srvRequest > uart_srvRequestPtr;
typedef boost::shared_ptr< ::uart::uart_srvRequest const> uart_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uart::uart_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uart::uart_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uart

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'uart': ['/home/odroid/cv_vision/src/uart/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uart::uart_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uart::uart_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uart::uart_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uart::uart_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uart::uart_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uart::uart_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uart::uart_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::uart::uart_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::uart::uart_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uart/uart_srvRequest";
  }

  static const char* value(const ::uart::uart_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uart::uart_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n\
";
  }

  static const char* value(const ::uart::uart_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uart::uart_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uart_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uart::uart_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uart::uart_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UART_MESSAGE_UART_SRVREQUEST_H
