# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uart/mpu6050.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mpu6050(genpy.Message):
  _md5sum = "ee542a682aee2ad96063f7f4b66160ba"
  _type = "uart/mpu6050"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 ax
int16 ay
int16 az
int16 gx
int16 gy
int16 gz
"""
  __slots__ = ['ax','ay','az','gx','gy','gz']
  _slot_types = ['int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ax,ay,az,gx,gy,gz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mpu6050, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ax is None:
        self.ax = 0
      if self.ay is None:
        self.ay = 0
      if self.az is None:
        self.az = 0
      if self.gx is None:
        self.gx = 0
      if self.gy is None:
        self.gy = 0
      if self.gz is None:
        self.gz = 0
    else:
      self.ax = 0
      self.ay = 0
      self.az = 0
      self.gx = 0
      self.gy = 0
      self.gz = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.ax, _x.ay, _x.az, _x.gx, _x.gy, _x.gz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.ax, _x.ay, _x.az, _x.gx, _x.gy, _x.gz,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.ax, _x.ay, _x.az, _x.gx, _x.gy, _x.gz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.ax, _x.ay, _x.az, _x.gx, _x.gy, _x.gz,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6h = None
def _get_struct_6h():
    global _struct_6h
    if _struct_6h is None:
        _struct_6h = struct.Struct("<6h")
    return _struct_6h
