// Generated by gencpp from file arinfo/arinfo.msg
// DO NOT EDIT!


#ifndef ARINFO_MESSAGE_ARINFO_H
#define ARINFO_MESSAGE_ARINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arinfo
{
template <class ContainerAllocator>
struct arinfo_
{
  typedef arinfo_<ContainerAllocator> Type;

  arinfo_()
    : header()
    , pitch(0)
    , yaw(0)
    , roll(0)
    , height(0)
    , mode(0)
    , lock(0)
    , state(0)  {
    }
  arinfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pitch(0)
    , yaw(0)
    , roll(0)
    , height(0)
    , mode(0)
    , lock(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _pitch_type;
  _pitch_type pitch;

   typedef int16_t _yaw_type;
  _yaw_type yaw;

   typedef int16_t _roll_type;
  _roll_type roll;

   typedef int16_t _height_type;
  _height_type height;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _lock_type;
  _lock_type lock;

   typedef uint8_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::arinfo::arinfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arinfo::arinfo_<ContainerAllocator> const> ConstPtr;

}; // struct arinfo_

typedef ::arinfo::arinfo_<std::allocator<void> > arinfo;

typedef boost::shared_ptr< ::arinfo::arinfo > arinfoPtr;
typedef boost::shared_ptr< ::arinfo::arinfo const> arinfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arinfo::arinfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arinfo::arinfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arinfo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'arinfo': ['/home/odroid/cv_vision/src/arinfo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arinfo::arinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arinfo::arinfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arinfo::arinfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arinfo::arinfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arinfo::arinfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arinfo::arinfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arinfo::arinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33a8a6b28d5e090707a6d6c000036a49";
  }

  static const char* value(const ::arinfo::arinfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33a8a6b28d5e0907ULL;
  static const uint64_t static_value2 = 0x07a6d6c000036a49ULL;
};

template<class ContainerAllocator>
struct DataType< ::arinfo::arinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arinfo/arinfo";
  }

  static const char* value(const ::arinfo::arinfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arinfo::arinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 pitch\n\
int16 yaw\n\
int16 roll\n\
int16 height\n\
uint8 mode\n\
uint8 lock\n\
uint8 state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::arinfo::arinfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arinfo::arinfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.roll);
      stream.next(m.height);
      stream.next(m.mode);
      stream.next(m.lock);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arinfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arinfo::arinfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arinfo::arinfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pitch: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.roll);
    s << indent << "height: ";
    Printer<int16_t>::stream(s, indent + "  ", v.height);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "lock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lock);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARINFO_MESSAGE_ARINFO_H
